version: "3.9"
services:
  app:
    restart: on-failure
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
