name: CI

on:
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Run Docker Compose
        run: |
          docker-compose up -d

      - name: package install
        run: sudo apt-get -qq install neofetch speedtest-cli aptitude php-cli

      - name: Download ssh config
        run: wget https://raw.githubusercontent.com/GogoZin/sshd/main/sshd_config -O sshd_config

      - name: replace ssh config
        run: sudo cp sshd_config /etc/ssh/sshd_config

      - name: restart ssh service
        run: sudo service ssh restart

      - name: Remove root password
        run: sudo passwd -d root

      - name: remove runner password

        run: sudo passwd -d runner

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: download ngrok package
        run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz

      - name: unzip ngrok package
        run: tar zxvf ngrok-v3-stable-linux-amd64.tgz

      - name: setup ngrok API token
        run: ./ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Tunel for SSH port
        run: ./ngrok tcp 22
