name: SSH INTO VM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run remote command
        uses: appleboy/ssh-action@master
        with:
          host: 0.tcp.jp.ngrok.io
          port: 16761
          username: nivekyang
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone https://github.com/nivek-yang/node-github-action.git
            cd node-github-action
            docker-compose up -d
